language: node_js
node_js:
  - stable
branches:
  only:
    - master
    - /^greenkeeper/.*$/
install:
  - npm install -g istanbul
  - npm install -g @angular/cli
before_script:
  - npm install
script:
  - echo "Beginning build and test cycle"
  - npm run lint
  - npm run build:ssr
  - npm run test:coverage
after_success:
  - echo "Uploading coverage reports"
  - bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
