language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^greenkeeper/.*$/
    - /^feat-.*$/
install:
  - npm install -g istanbul
  - npm install -g @angular/cli
  - npm install -g firebase-tools
before_script:
  - npm install
  - cd functions && npm install && cd ..
script:
  - echo "Beginning build and test cycle"
  - npm run lint || travis_terminate 1
  - npm run build:ssr || travis_terminate 1
  - cd functions && npm run deploy && cd .. || travis_terminate 1
  - npm run test:coverage
after_success:
  - echo "Uploading coverage reports"
  - bash <(curl -s https://codecov.io/bash)
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
